name: Lint & Deploy to Render

on:
  push:
    branches:
      - main
      - develop

jobs:
  lint:
    name: ESLint check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

  deploy:
    # lintジョブが成功かつ、mainブランチにpushされたときのみ実行
    name: Build & Deploy to Render (only on main)
    needs: lint # lint成功時にのみ実行
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to Render via Webhook
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
